config/routes.rb
Rails.application.routes.draw do
  root  to: 'users#show'
  resources :groups
  resources :time_blocks
  devise_for :users, :controllers => {:sessions => "devise/sessions", registrations: 'registrations'}
  
  resources :users, only: [:show]

  get 'nongrouped', to: 'time_blocks#nongrouped', as: 'nongrouped'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { in: 3..12 }
  belongs_to :user
  has_many :groupings, dependent: :destroy
  has_many :time_blocks, through: :groupings

  has_one_attached :icon, dependent: :destroy
end

app/models/grouping.rb
class Grouping < ApplicationRecord
  belongs_to :time_block
  belongs_to :group
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  enum status: { pending: 0, failed: 1, paid: 2 }
  enum payment_gateway: { stripe: 0 }
  belongs_to :subscription_plan
  belongs_to :user

  scope :recently_created, -> { where(created_at: 1.minutes.ago..DateTime.now) }

  def set_paid
    self.status = Subscription.statuses[:paid]
  end

  def set_failed
    self.status = Subscription.statuses[:failed]
  end
end

app/models/subscription_plan.rb
class SubscriptionPlan < ActiveRecord::Base
  monetize :price_cents
  has_many :subscriptions
end

app/models/time_block.rb
class TimeBlock < ApplicationRecord
  validates :name, presence: true, length: { in: 3..15 }
  validates :amount, presence: true
  belongs_to :author, class_name: 'User'
  has_many :groupings, dependent: :destroy
  has_many :groups, through: :groupings

  def self.non_grouped
    left_outer_joins(:groups).where('group_id is null')
  end

  def group_list
    # &:name works like {|x| x.name} and was changed by rubocop
    groups.collect(&:name).join(', ')
  end

  def group_list=(groups_string)
    group_names = groups_string.split(',').collect { |s| s.strip.downcase }.uniq
    found_groups = group_names.collect { |name| Group.find_by_name(name) }
    self.groups = found_groups
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true,
                       length: { in: 3..12 },
                       uniqueness: true

  has_many :time_blocks, foreign_key: :author_id
  has_many :groups

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value',\
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[username email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @groups = Group.all.includes(icon_attachment: :blob)
  end

  def show
    @time_blocks = @group.time_blocks.includes(:author).order('created_at DESC')
  end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = current_user.groups.create(group_params)

    respond_to do |format|
      if @group.valid?
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confiramtion)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confiramtion, :current_password)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  def index
    subscription_plan = SubscriptionPlan.all
    @plan_purchases = subscription_plan.where(stripe_plan_name: nil)
    # @products_subscription = products - @products_purchase
  end

  def submit; end
end

app/controllers/time_blocks_controller.rb
class TimeBlocksController < ApplicationController
  before_action :set_time_block, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @time_blocks = current_user.time_blocks.order('created_at DESC')
  end

  def show
    @groups = @time_block.groups.includes(icon_attachment: :blob)
  end

  def new
    @time_block = current_user.time_blocks.build
  end

  def edit; end

  def create
    @time_block = current_user.time_blocks.create(time_block_params)

    respond_to do |format|
      if @time_block.save
        format.html { redirect_to @time_block, notice: 'Time block was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @time_block.update(time_block_params)
        format.html { redirect_to @time_block, notice: 'Time block was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @time_block.destroy
    respond_to do |format|
      format.html { redirect_to time_blocks_url, notice: 'Time block was successfully destroyed.' }
    end
  end

  private

  def set_time_block
    @time_block = TimeBlock.find(params[:id])
    redirect_to current_user, notice: 'Access Forbidden' unless current_user.time_blocks.include?(@time_block)
  end

  def time_block_params
    params.require(:time_block).permit(:name, :amount, :group_list, :group, { group_ids: [] }, :group_ids)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_notice
    if alert || notice
      nil
    else
      'd-none'
    end
  end

  def background_style
    return if current_user.nil?

    if current_page?(user_path(current_user)) ||
       current_page?('/') ||
       (current_page?(controller: 'groups') &&
       current_page?(action: 'index'))
      'bg-gradient-blue'
    else
      'bg-light-grey'
    end
  end

  def bg(style)
    return '-light' if style == 'bg-gradient-blue'
  end

  def logged_in_nav
    return unless current_user

    link_to('Profile', user_path(current_user), class: "btn#{bg(background_style)} mb-1 p-2")
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_icon(group)
    if group.nil? || !group.icon.attached?
      image_tag 'icon_holder.png', class: 'icon'
    else
      image_tag group.icon, class: 'icon'
    end
  end
end

app/helpers/time_blocks_helper.rb
module TimeBlocksHelper
  def main_group_icon(time_block)
    if time_block.groups.first.nil? || !time_block.groups.first.icon.attached?
      image_tag 'icon_holder.png', class: 'icon'
    else
      image_tag time_block.groups.first.icon, class: 'icon'
    end
  end
end

app/views/groups/_form.html.erb
<%= simple_form_for @group do |form| %>
    <%= form.error_notification %>
    <%= form.input :name %>
    <%= form.input :icon %>
    <%= form.submit 'Create/Update Group' %>
<% end %>

app/views/groups/edit.html.erb
<h1 class='text-center'>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group, class:'btn p-1' %>
<%= link_to 'Back', groups_path, class:'btn p-1' %>

app/views/groups/index.html.erb
<h1 class='white'>Groups</h1>
  <% @groups.each do |group| %>
      <%= link_to group, class:'list-item-light d-flex justify-content-between p-2' do%>
        <div class='p-2'><%= group_icon(group) %></div>
        <div class='p-2 white'><%= group.name %></div>
        <div class="p-2 white date"><%= group.created_at.strftime("%e %b %Y") %></div>
      <% end %>
  <% end %>
<%= link_to 'New Group', new_group_path, class:'btn-light p-2 mt-2 mb-2' %>

app/views/groups/new.html.erb
<h1 class='text-center'>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path, class:'btn p-1' %>

app/views/groups/show.html.erb
  <h2 class='bg-gradient-blue white p-2 text-center mr-n2 ml-n2 w-100'>Group Time Blocks</h2>
  <strong class='m-2'>Name: <%= @group.name %></strong>
  <strong class='m-2'>Icon: <%= group_icon(@group) %></strong>  
  <div class='d-flex justify-content-between w-100'>
      <h4>Total Amount:</h4><h4><%= @time_blocks.sum("amount")%>H</h4>
  </div>
  <% @time_blocks.each do |block| %>
    <%= link_to block, class:'d-flex justify-content-between list-item mb-1 pt-1' do%>
      <div class='d-flex flex-column justify-content-between'>
        <div class='d-flex justify-content-between flex-wrap'>
          <div><%= block.name %></div>
          <div><%= block.author.username %></div>
        </div>
        <div class="date"><%= block.created_at.strftime("%e %b %Y") %></div>
      </div>
      <div><%= block.amount %>H</div>
    <% end %>
  <% end %>

  <%= link_to 'Destroy Group', @group, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn mb-2' %>
  <%= link_to 'Edit Group', edit_group_path(@group), class:'btn mb-2' %>
  <%= link_to 'Back', groups_path, class:'btn mb-2' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReadingHour</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class='d-flex flex-column justify-content-center align-items-center <%= background_style %>'>
    <p id="alert" class=<%=alert_notice%> ><%= alert %></p>
    <p id="notice" class=<%=alert_notice%> ><%= notice %></p>
    <%= logged_in_nav %>
    <%= yield %>
      
  </body>
</html>

app/views/subscriptions/index.html.erb
<%= stripe_javascript_tag %>
<div>
  <h1>List of plans</h1>
  <%= form_tag({:controller => "subscriptions", :action => "submit" }, {:id => 'subscription-details'}) do %>
    <input id="order-type" name="subscriptions[payment_gateway]" type="hidden" value="stripe"></input>
    <div class="form_row">
      <h4>Charges/Payments</h4>
      <% @plan_purchases.each do |plan| %>
        <div data-charges-and-payments-section="<%= true %>">
          <%= radio_button_tag 'subscriptions[subscription_plan_id]', plan.id, @plan_purchases.first == plan %>
          <span id="radioButtonName<%= plan.id %>"><%=plan.name%></span>
          <span data-price="<%= plan.price_cents %>" id="radioButtonPrice<%= plan.id %>"><%= humanized_money_with_symbol plan.price%></span>
        </div>
        <br/>
      <% end %>
    </div>
    <hr/>
    <h1>Payment Method</h1>
    <div class="form_row">
      <div>
        <%= radio_button_tag 'payment-selection', 'stripe', true, onclick: "changeTab();" %>
        <span>Stripe</span>
      </div>
    </div>
    <br/>
    <br/>
    <div class="paymentSelectionTab active" id="tab-stripe">
      <div id="card-element"></div>
      <div id="card-errors" role="alert"></div>
      <br/>
      <br/>
      <%= submit_tag "Buy it!", id: "submit-stripe" %>
    </div>
    <div class="paymentSelectionTab" id="tab-paypal">
      <div id="submit-paypal"></div>
    </div>
    <br/>
    <br/>
    <hr/>
  <% end %>
</div>
<script>
  
  function changeTab() {
    var newActiveTabID = $('input[name="payment-selection"]:checked').val();
    $('.paymentSelectionTab').removeClass('active');
    $('#tab-' + newActiveTabID).addClass('active');
  }


</script>
<style>
  
  #card-element {
    width:500px;
  }
  .paymentSelectionTab {
    display: none;
  }
  .paymentSelectionTab.active {
    display: block !important;
  }

</style>

app/views/time_blocks/_form.html.erb
<%= simple_form_for @time_block do |f| %>
  <%= f.error_notification %>
  
  <%= f.input :name %> 
  <%= f.input :amount, placeholder:'in hours' %>
  <%= f.input :group_ids, as: :select, collection: Group.all, label_method: :name, input_html: {multiple: true} %>

  <%= f.submit 'Create/Update Time Block'%>
  
<% end %>
<script>
  $(window).load( function(){
    $('#time_block_group_ids').chosen({
      allow_single_deselect:true,
      width: '100%'
    })
  });
</script>

app/views/time_blocks/edit.html.erb
<h1 class='text-center'>Editing Time Block</h1>

<%= render 'form', time_block: @time_block %>

<%= link_to 'Show', @time_block, class:'btn p-1' %>
<%= link_to 'Back', time_blocks_path, class:'btn p-1' %>

app/views/time_blocks/index.html.erb
  <h2 class='bg-gradient-blue white text-center mr-n2 ml-n2 w-100'>Time Blocks</h2>
  <div class='d-flex justify-content-between w-100'>
    <h4>Total Amount:</h4><h4><%= @time_blocks.sum("amount")%>H</h4>
  </div>

  <% @time_blocks.each do |block| %>
    <%= link_to block, class:'d-flex justify-content-between list-item mb-1 pt-1' do%>
      <div class='d-flex flex-column justify-content-between'>
        <div class='d-flex'>
          <div><%= main_group_icon(block) %></div>
          <div><%= block.name %></div>
        </div>
        <div class="date"><%= block.created_at.strftime("%e %b %Y") %></div>
      </div>
      <div><%= block.amount %>H</div>
    <% end %>
  <% end %>

  <%= link_to 'New Time Block', new_time_block_path, class:'btn-primary p-1' %>

app/views/time_blocks/new.html.erb
<h1 class='text-center'>New Time Block</h1>

<%= render 'form', time_block: @time_block %>

<%= link_to 'Back', time_blocks_path, class:'btn p-1' %>

app/views/time_blocks/nongrouped.html.erb
<div class='d-flex flex-column pr-2 pl-2'>
  <h1 class='bg-gradient-blue white text-center mr-n2 ml-n2'>Non-Grouped Time Blocks</h1>
  <div class='d-flex justify-content-between w-100'>
    <h4>Total Amount:</h4><h4><%= TimeBlock.non_grouped.sum("amount")%>H</h4>
  </div>

  <% TimeBlock.non_grouped.each do |block| %>
    <%= link_to block, class:'d-flex justify-content-between list-item mb-1 pt-1' do%>
      <div class='d-flex flex-column justify-content-between'>
        <div class='d-flex'>
          <div><%= main_group_icon(block) %></div>
          <div><%= block.name %></div>
        </div>
        <div class="date"><%= block.created_at.strftime("%e %b %Y") %></div>
      </div>
      <div><%= block.amount %>H</div>
    <% end %>
  <% end %>

  <%= link_to 'New Time Block', new_time_block_path, class:'btn-primary p-1' %>
</div>

app/views/time_blocks/show.html.erb
<div class='d-flex flex-column p-2'>
  <strong class='m-2'>Name: <%= @time_block.name %></strong>  
  <strong class='m-2'>Amount: <%= @time_block.amount %></strong>
  <strong class='m-2'>Groups:</strong>
  <% @groups.each do |group|%>
    <%= link_to group, class:'list-item d-flex justify-content-between p-2' do%>
      <div class='p-2'><%= group_icon(group) %></div>
      <div class='p-2'><%= group.name %></div>
      <div class="p-2 date"><%= group.created_at.strftime("%e %b %Y") %></div>
    <% end %>
  <% end %>
  
  <%= link_to 'Destroy Time Block', @time_block, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn p-1' %>
  <%= link_to 'Edit Time Block', edit_time_block_path(@time_block), class:'btn p-1' %>
  <%= link_to 'Back', time_blocks_path, class:'btn p-1' %>
</div>

app/views/users/show.html.erb
<div class="text-center white">
  <div>
    <p>Hello <%= @user.username %></p>
  </div>
  <div class='d-flex flex-column text-center'>
    <%= link_to 'All Groups', groups_path, class:'btn-light profile-btn'%>
    <%= link_to 'non-grouped spans', nongrouped_path, class:'btn-light profile-btn'%>
    <%= link_to 'My Reading spans', time_blocks_path, class:'btn-light profile-btn'%>
    <%= link_to 'Edit Profile', edit_user_registration_path(@user), class:'btn-light profile-btn'%>
    <%= link_to 'Log Out', destroy_user_session_path, method: :delete,\
                                                  class: "btn#{bg(background_style)} mb-1 p-2"%>
  </div>
</div>